
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true


  application:
     name: WorkspaceApiGateway
server:
  port: 9142
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:9001/eureka

logging:
  level:
    org:
      springframework:
        web:
          DEBUG