
spring:
  jpa:
    hibernate:
      ddl-auto: create
  application:
     name: UserService

server:
   port: 8008
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:9001/eureka

logging:
  level:
    org:
      springframework:
        web:
          DEBUG

