logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
            descriptor:
              sql:
                BasicBinder: TRACE
      springframework:
        boot:
          autoconfigure:
            orm:
              jpa: DEBUG
spring:
  datasource:
    easyapply:
      url: jdbc:sqlserver://LAPTOP-855CFJLD\SQLEXPRESS:1433;databaseName=EasyApply;encrypt=true;trustServerCertificate=true
      username: admin
      password: admin123
      driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: create
      generate-ddl : true
      dialect: org.hibernate.dialect.SQLServerDialect
  application:
     name: UserService

server:
   port: 8008
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone : http://localhost:9001/eureka
